# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build adapt`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t adapt`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app
COPY ./ /app

RUN addgroup --system adapt && \
          adduser --system -G adapt adapt
RUN npm install -g pnpm
RUN pnpm install
RUN pnpm run build

RUN chown -R adapt:adapt .

CMD [ "node", "dist/adapt/main.js" ]
