# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions: # add permissions to be able to authenticate in gihub container registry
  contents: read
  packages: write

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['20.x']
        pnpm-version: [8]

    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v3
      with:
        version: ${{ matrix.pnpm-version }}
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - run: pnpm install --frozen-lockfile
    - run: pnpm build
    - run: pnpm test
    - run: docker build -t ghcr.io/adapt/api/api_docker_image_name .
    - run: docker images
    - run: docker push ghcr.io/adapt/api/api_docker_image_name:latest
    - run: docker pull ghcr.io/adapt/api/api_docker_image_name


        
